
# Server Configuration
server:
  port: 3000
  host: "localhost"

# Database Configuration
database:
  mysql:
    dsn: "root:admin@tcp(localhost:3306)/rellic_iofi?charset=utf8mb4&parseTime=True&loc=Local"
  redis:
    addr: "localhost:6379"
    password: ""
    db: 0

