# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: "Release build"

on:
  push:
    tags:
      - "*"

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: "Set up Go"
      uses: actions/setup-go@v4
      with:
        go-version: '1.21.3'
        cache-dependency-path: .cached/go.sum
      id: go
    - name: "Run GoReleaser"
      uses: goreleaser/goreleaser-action@master
      with:
        version: latest
        args: release --rm-dist
      env:
        GITHUB_TOKEN: ${{ secrets.GO_RELEASER_GITHUB_TOKEN }}
